[package]
name = "nexq"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
  "crates/core",
  "crates/backends/*"
]

[dependencies]
nexq-core = { path = "crates/core" }
mio = { version = "0.8.9", features = ["net", "os-poll"] }
