[package]
name = "nerfq"
version = "0.1.0"
edition = "2021"

[dependencies]
crossbeam-utils = "0.8.16"
crossbeam-queue = "0.3.8"
dashmap = "5.5.3"
time = "0.3.30"
ulid = { version = "1.1.0" }
nanorand = "0.7.0"
